<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>ru.kultishov</groupId>
        <artifactId>rpm-parent</artifactId>
        <version>1.0.0-SNAPSHOT</version>
    </parent>

    <artifactId>demo</artifactId>
    <packaging>jar</packaging>

    <build>
        <plugins>
            <plugin>
                <groupId>ru.kultishov</groupId>
                <artifactId>rpm-maven-plugin</artifactId>
                <version>${project.version}</version>
                <configuration>
                    <mappings>
                        <mapping>
                            <destination>/etc/demo</destination>
                            <mode>0755</mode>
                        </mapping>
                        <mapping>
                            <source>${project.basedir}/src/main/rpm/demo.properties</source>
                            <destination>/etc/demo/demo.properties</destination>
                            <mode>0644</mode>
                            <owner>root</owner>
                            <group>root</group>
                            <config>true</config>
                        </mapping>
                        <mapping>
                            <destination>/var/log/demo</destination>
                            <mode>0755</mode>
                        </mapping>
                    </mappings>
                </configuration>
                <executions>
                    <execution>
                        <id>rpm-package</id>
                        <phase>package</phase>
                        <goals>
                            <goal>prepare</goal>
                            <goal>build</goal>
                            <goal>verify</goal>
                        </goals>
                    </execution>
                </executions>
            </plugin>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-jar-plugin</artifactId>
                <version>3.4.2</version>
                <configuration>
                    <archive>
                        <manifest>
                            <mainClass>ru.kultishov.demo.DemoServer</mainClass>
                        </manifest>
                    </archive>
                </configuration>
            </plugin>
        </plugins>
    </build>
</project>
