package ru.kultishov.rpm;

import org.apache.maven.plugin.MojoExecutionException;

import java.io.IOException;
import java.io.Reader;
import java.io.Writer;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.Instant;
import java.time.ZoneOffset;
import java.time.format.DateTimeFormatter;
import java.util.Locale;
import java.util.Properties;
import java.util.regex.Matcher;
import java.util.regex.Pattern;

record RpmPackage(String name, String version, String release, String jarPath, String jreRequirement) {
    private static final Pattern MAVEN_VERSION = Pattern.compile("([0-9]+(?:\\.[0-9]+)+)(?:-(RC[0-9]+|SNAPSHOT))?");
    private static final Pattern PACKAGE_NAME = Pattern.compile("[a-z0-9][a-z0-9+._-]*");
    private static final Pattern REQUIREMENT = Pattern.compile(
            "[a-zA-Z0-9][a-zA-Z0-9+._-]*(?: (?:>=|<=|=|>|<) [0-9][a-zA-Z0-9.:~+_-]*)?");
    private static final DateTimeFormatter TIMESTAMP = DateTimeFormatter.ofPattern("yyyyMMddHHmmss", Locale.ROOT)
            .withZone(ZoneOffset.UTC);
    private static final DateTimeFormatter CHANGELOG_DATE = DateTimeFormatter.ofPattern("EEE MMM dd yyyy", Locale.ENGLISH)
            .withZone(ZoneOffset.UTC);

    static RpmPackage create(String name, String mavenVersion, int releaseNumber, String jreRequirement,
                             Instant buildTime) throws MojoExecutionException {
        if (name == null || !PACKAGE_NAME.matcher(name).matches()) {
            throw new MojoExecutionException("RPM name must contain only lowercase letters, digits, '.', '+', '_' or '-'");
        }
        if (releaseNumber < 1) {
            throw new MojoExecutionException("RPM release number must be positive");
        }
        jreRequirement = normalizeRequirement(jreRequirement);
        Matcher matcher = MAVEN_VERSION.matcher(mavenVersion);
        if (!matcher.matches()) {
            throw new MojoExecutionException("Unsupported Maven version: " + mavenVersion);
        }
        String version = matcher.group(1);
        String qualifier = matcher.group(2);
        if (qualifier != null) {
            if (qualifier.equals("SNAPSHOT")) {
                version += "~snapshot." + TIMESTAMP.format(buildTime);
            } else {
                version += "~" + qualifier.toLowerCase(Locale.ROOT);
            }
        }
        return new RpmPackage(name, version, "alt" + releaseNumber,
                "/usr/share/" + name + "/" + name + ".jar", jreRequirement);
    }

    static String changelogDate(Instant buildTime) {
        return CHANGELOG_DATE.format(buildTime);
    }

    static String normalizeRequirement(String requirement) throws MojoExecutionException {
        if (requirement == null || requirement.indexOf('\n') >= 0 || requirement.indexOf('\r') >= 0) {
            throw new MojoExecutionException("JRE requirement must be a single package name with an optional version constraint");
        }
        String normalized = requirement.trim().replaceAll("[ \\t]+", " ");
        if (!REQUIREMENT.matcher(normalized).matches()) {
            throw new MojoExecutionException("Invalid JRE requirement: use a package name, optionally followed by an operator and version");
        }
        return normalized;
    }

    String installDirectory() {
        return "/usr/share/" + name;
    }

    Path rpmFile(Path workDirectory) {
        return workDirectory.resolve("RPMS/noarch/" + name + "-" + version + "-" + release + ".noarch.rpm");
    }

    void save(Path file) throws IOException {
        Properties properties = new Properties();
        properties.setProperty("name", name);
        properties.setProperty("version", version);
        properties.setProperty("release", release);
        properties.setProperty("jarPath", jarPath);
        properties.setProperty("jreRequirement", jreRequirement);
        try (Writer writer = Files.newBufferedWriter(file)) {
            properties.store(writer, "Generated by rpm-maven-plugin");
        }
    }

    static RpmPackage load(Path file) throws IOException, MojoExecutionException {
        if (!Files.isRegularFile(file) || Files.isSymbolicLink(file)) {
            throw new MojoExecutionException("RPM preparation metadata is missing: " + file);
        }
        Properties properties = new Properties();
        try (Reader reader = Files.newBufferedReader(file)) {
            properties.load(reader);
        }
        String name = properties.getProperty("name");
        String version = properties.getProperty("version");
        String release = properties.getProperty("release");
        String jarPath = properties.getProperty("jarPath");
        String jreRequirement = properties.getProperty("jreRequirement");
        if (name == null || !PACKAGE_NAME.matcher(name).matches()
                || version == null || !version.matches("[0-9.]+(?:~[a-z0-9.]+)?")
                || release == null || !release.matches("alt[1-9][0-9]*")
                || !(("/usr/share/" + name + "/" + name + ".jar").equals(jarPath))
                || jreRequirement == null || !REQUIREMENT.matcher(jreRequirement).matches()) {
            throw new MojoExecutionException("Invalid RPM preparation metadata: " + file);
        }
        return new RpmPackage(name, version, release, jarPath, jreRequirement);
    }
}
